name: Deploy

on:  
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [release-please]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git
          branch: ${{ inputs.branch }}