name: Hotfix

on:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_branch: release/v${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - run: npm run release
      - id: version
        run: |
            VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
            echo ::set-output name=version::$VERSION
      - run: git push --follow-tags origin release/v${{ steps.version.outputs.version }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [release]
    environment: stg
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.release.outputs.release_branch }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git
          branch: ${{ needs.release.outputs.release_branch }}
  
  deploy-production:
    runs-on: ubuntu-latest
    needs: [release, deploy-staging]
    environment: prd
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.release.outputs.release_branch }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git
          branch: ${{ needs.release.outputs.release_branch }}

  create-pull-request:
    runs-on: ubuntu-latest
    needs: [release, deploy-production]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.release.outputs.release_branch }}
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ needs.release.outputs.release_branch }}
          destination_branch: main
          pr_title: "hotfix: ${{ needs.release.outputs.release_branch }}"
          pr_body: "This is an automatically created pull request to bring the main branch up-to-date with a hotfix deployed to a release branch."
          pr_label: "auto"