name: Release & Deploy

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type": "build", "section": "Other"},
                            {"type": "ci", "section": "Other"},
                            {"type": "chore", "section": "Other"},
                            {"type": "docs", "section": "Other"},
                            {"type": "feat", "section": "Features"},
                            {"type": "fix", "section": "Bug Fixes"},
                            {"type": "perf", "section": "Other"},
                            {"type": "refactor", "section": "Other"},
                            {"type": "revert", "hidden": true},
                            {"type": "style", "section": "Other"},
                            {"type": "test", "section": "Other"}]'

  deploy-staging:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git

  deploy-production:
    runs-on: ubuntu-latest
    environment: prd
    needs: [deploy-staging, release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git