name: Release

on:
  push:
    branches:
      - main
      - release/**

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: release-please-action
          default-branch: ${{ github.ref_name }}
          changelog-types: '[{"type": "build", "section": "Other"},
                            {"type": "ci", "section": "Other"},
                            {"type": "chore", "section": "Other"},
                            {"type": "docs", "section": "Other"},
                            {"type": "feat", "section": "Features"},
                            {"type": "fix", "section": "Bug Fixes"},
                            {"type": "perf", "section": "Other"},
                            {"type": "refactor", "section": "Other"},
                            {"type": "revert", "hidden": true},
                            {"type": "style", "section": "Other"},
                            {"type": "test", "section": "Other"}]'

  deploy-staging:
    runs-on: ubuntu-latest
    environment: stg
    needs: [release-please]
    if: ${{ !needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git

  create-release-branch:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    env:
      RELEASE_BRANCH: release/${{ needs.release-please.outputs.tag_name }}
    outputs:
      release_branch: ${{ env.RELEASE_BRANCH }}
    steps:
      - uses: actions/checkout@v2
      - name: Create release branch
        run: git checkout -b ${{ env.RELEASE_BRANCH }}
      - name: Push new branch
        run: git push origin ${{ env.RELEASE_BRANCH }}

  create-pull-request:
    runs-on: ubuntu-latest
    needs: [create-release-branch]
    if: ${{ startsWith(github.ref_name, release/) }}
    env:
      RELEASE_BRANCH: ${{ needs.create-release-branch.outputs.release_branch }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_BRANCH }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.RELEASE_BRANCH }}
          base: main
          title: 'hotfix: ${{ env.RELEASE_BRANCH }}'
          description: 'This pull request is automatically generated when a hotfix is deployed
                        to a release branch. Merge this pull request to include the hotfix
                        in the main branch.'

  deploy-production:
    runs-on: ubuntu-latest
    environment: prd
    needs: [create-release-branch]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.create-release-branch.outputs.release_branch }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: https://github.com/mars/create-react-app-buildpack.git